name: 'publish'
on:
  push:
    branches:
      - tauri-example-postgres

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04]
        # platform: [macos-latest, ubuntu-20.04, windows-latest]


    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8

      # We need this to get docker on macOS
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: install frontend dependencies
        run: cd ./generator/ && pnpm install --no-frozen-lockfile && pnpm build && cd .. && cd ./clients/typescript/ && pnpm install --no-frozen-lockfile && pnpm build && cd ../../ && cd ./examples/tauri-postgres/ && pnpm install --no-frozen-lockfile && pnpm backend:up && sleep 5 && pnpm db:migrate && sleep 5 && pnpm run client:generate && sleep 5 && bash patch.sh && pnpm install --no-frozen-lockfile # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          projectPath: './examples/tauri-postgres/'
          tauriScript: pnpm tauri
